### ISSUE TITLE
Unranked games

### ISSUE THREAD

**Issue by alexbouchard** [busbud/pongdome#20]
`#(open)challenge` `#forfun`

**Comment by valeriangalliat** [comment]
* Need to modify the chat module to have all tags that are not in the actions object to be passed as argument to the action.
* Then add an `unranked` property to the challenge object in case it's `#forfun` or `#unranked`.
* On the API side, do not persist state at the end if `challenge.unranked`.
* On frontend side, show in some way that the current game is unranked. cc @pecpec

**Comment by valeriangalliat** [comment]
UI could be better, but for now it's good enough.
