### ISSUE TITLE
Bluetooth beacons and apps

### ISSUE THREAD

**Issue by valeriangalliat** [busbud/pongdome#28]
Install bluetooth beacons on each side of the table.

The user installs an app and logs in in some way that can be matched by the system (if we don't have the chat system ID currently used as user ID, we could try to match by email with a Google login for example).

When the smartphone is in range of the beacon, it sends an API request "user X is available to play on Y side". When the smartphone gets out of range, it sends a request to remove availability (it should also timeout on API side).

If two players are in position to play, PongDome starts a game.

Need a way on the app to cancel the game.

**Comment by xzoky** [comment]
👏🏻
